export type GalleryImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  landscape: boolean;
  size: string;
  offsetX: number;
  offsetY: number;
  title: string;
  technique: string;
  dimentions: string;
  date: string;
};

export const images: GalleryImage[] = [
  {
    src: "/images/blurb/Pieza titulada quince en tecnica mixta sobre tela 217x 122 cm 2001 por artista plastico enrique ciapara.webp",
    alt: "Pieza titulada quince en tecnica mixta sobre tela 217x 122 cm  creada en 2001 por artista plastico enrique ciapara basado en Tijuana",
    width: 341,
    height: 606,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Quince",
    technique: "Mixta sobre tela",
    dimentions: "217 x 122 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Pieza sin tiulo en acrilico sobre tela 217 x 122 cm por artista visual bajacaliforniano ciapara.webp",
    alt: "Pieza sin título en acrílico sobre tela 217 x 122 cm por artista visual bajacaliforniano Enrique Ciapara",
    width: 337,
    height: 605,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Sin título",
    technique: "Acrílico sobre tela",
    dimentions: "217 x 122 cm",
    date: "-",
  },
  {
    src: "/images/blurb/Pieza detritus elaborada en acrilico sobre tela 217x 122 cm en 1999 por enrique ciapara.webp",
    alt: "Pieza detritus elaborada en acrílico sobre tela 217x 122 cm en 1999 por Enrique Ciapara",
    width: 349,
    height: 604,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Detritus",
    technique: "Acrílico sobre tela",
    dimentions: "217 x 122 cm",
    date: "( 1999 )",
  },
  {
    src: "/images/blurb/Pieza caminata en tecnica mixta sobre tela 183x 305 cm 2008 por enrique ciapara.webp",
    alt: "Pieza caminata en técnica mixta sobre tela 183x 305 cm elaborada en 2008 por artista Enrique Ciapara",
    width: 770,
    height: 475,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Caminata",
    technique: "Mixta sobre tela",
    dimentions: "183 x 305 cm ",
    date: "( 2008 )",
  },
  {
    src: "/images/blurb/La despedida pieza en acrilico sobre tela en 122x 213 cm por Enrique Ciapara.webp",
    alt: "La despedida pieza elaborada en acrílico sobre tela en 122x 213 cm por el artista de la frontera San Diego Tijuana Enrique Ciapara",
    width: 770,
    height: 442,
    landscape: false,
    size: "w-full",
    offsetX: -10,
    offsetY: 16,
    title: "La despedida",
    technique: "Acrílico sobre tela",
    dimentions: "122 x 213 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/Pieza titulada detritus en tinta sobre papel 101x 406 cm elaborada en 2005 por artista mexicano enrique ciapara.webp",
    alt: "Pieza titulada detritus en tinta sobre papel 101x 406 cm elaborada en 2005 por artista mexicano enrique ciapara",
    width: 770,
    height: 194,
    landscape: true,
    size: "w-full",
    offsetX: 0,
    offsetY: 0,
    title: "Detritus",
    technique: "Tinta sobre papel",
    dimentions: "101 x 406 cm",
    date: "( 2005 )",
  },
  {
    src: "/images/blurb/Pieza sin titulo elaborada en tecnica mixta sobre papel en 130x 90 cm por arista abstracto enrique ciapara.webp",
    alt: "Pieza sin título elaborada en técnica mixta sobre papel en 130x 90 cm por arista abstracto mexicano Enrique Ciapara",
    width: 430,
    height: 609,
    landscape: false,
    size: "w-[85%]",
    offsetX: -12,
    offsetY: 14,
    title: "Sin título",
    technique: "Mixta sobre papel",
    dimentions: "130 x 90 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Obra el inmortal  en tecnica mixta sobre papel en 130x 90 cm elaborada en 2001 por Enrique Ciapara artista de la frontera sandiego tijuana.webp",
    alt: "Obra el inmortal en técnica mixta sobre papel en 130 x 90 cm elaborada en 2001 por el artista plástico Enrique Ciapara que vive en la frontera San Diego Tijuana ",
    width: 452,
    height: 607,
    landscape: false,
    size: "w-[90%]",
    offsetX: 18,
    offsetY: -16,
    title: "El inmortal",
    technique: "Mixta sobre papel",
    dimentions: "130 x 90 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Obra sin titulo  pieza en tecnica mixta sobre papel en 130x 90 cm por el pintor enrique ciapara.webp",
    alt: "Obra sin titulo en técnica mixta sobre papel en 130x 90 cm por el pintor mexicano Enrique Ciapara",
    width: 449,
    height: 603,
    landscape: false,
    size: "w-full",
    offsetX: -16,
    offsetY: 18,
    title: "Sin título",
    technique: "Mixta sobre papel",
    dimentions: "130 x 90 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Avión y pimiento mixta sobre papel 60 x 40 cm 2002 .webp",
    alt: "Obra titulada avión y pimiento en técnica mixta sobre papel 60x 40 cm por Enrique Ciapara artista de la región Tijuana San Diego",
    width: 336,
    height: 529,
    landscape: false,
    size: "w-[88%]",
    offsetX: 14,
    offsetY: -14,
    title: "Avión y pimiento",
    technique: "Mixta sobre papel",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
  {
    src: "/images/blurb/Imago mixta sobre tela 213x 122 cm 2001.webp",
    alt: "Imago pieza en técnica mixta sobre tela en dimensiones de  213 x 122 cm por artista mexicano  Enrique Ciapara",
    width: 611,
    height: 529,
    landscape: false,
    size: "w-[85%]",
    offsetX: -10,
    offsetY: 16,
    title: "Imago",
    technique: "Mixta sobre tela",
    dimentions: "213 x 122 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Las cosas y las sombras de las cosas mixta sobre tela 213 x 122 cm 2001 .webp",
    alt: "Obra del archivo de Enrique Ciapara titulada: las cosas y las sombras de las cosas en técnica mixta sobre tela 213x 122 cm  ",
    width: 304,
    height: 525,
    landscape: false,
    size: "w-[90%]",
    offsetX: 16,
    offsetY: -18,
    title: "Las cosas y las sombras de las cosas",
    technique: "Mixta sobre tela",
    dimentions: "213 x 122 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Sin titulo mixta sobre papel 60x 40 cm 2002.webp",
    alt: "Obra de archivo 2000-09 por Enrique Ciapara en técnica mixta sobre papel en 60x 40 cm  ",
    width: 333,
    height: 527,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Sin título",
    technique: "Mixta sobre papel",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
  {
    src: "/images/blurb/alt camp mixta sobre tela 213x 122 cm 2003.webp",
    alt: "Pieza titulada alt camp en técnica mixta sobre tela en dimensiones 213x 122 cm por Enrique Ciapara",
    width: 302,
    height: 528,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Alt camp",
    technique: "Mixta sobre tela",
    dimentions: "213 x 122 cm",
    date: "( 2003 )",
  },
  {
    src: "/images/blurb/delerrictus mixta sobre tela 213x 122 cm 2001.webp",
    alt: "Pieza titulada delerrictus por Enrique Ciapara en técnica mixta sobre tela 213x 122 cm de tu archivo  2000-09 ",
    width: 294,
    height: 527,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Delerrictus",
    technique: "Mixta sobre tela",
    dimentions: "213 x 122 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/dibujo mixta sobre tela 122x 107 cm 2006.webp",
    alt: "Pieza llamada dibujo en técnica sobre tela en 122x 107 cm del pintor Enrique Ciapara",
    width: 465,
    height: 528,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Dibujo",
    technique: "Mixta sobre tela",
    dimentions: "122 x 107 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/el conejo u el león mixta sobre tela 200x 200 2005.webp",
    alt: "Pieza El conejo y el leon por Enrique Ciapara en técnica mixta sobre tela 200x200 del archivo 2000-09",
    width: 539,
    height: 528,
    landscape: false,
    size: "w-full",
    offsetX: -10,
    offsetY: 16,
    title: "El conejo en el león",
    technique: "Mixta sobre tela",
    dimentions: "200 x 200",
    date: "( 2005 )",
  },
  {
    src: "/images/blurb/habitación amarilla con pipa mixta sobre papel 60x 40 cm 2003.webp",
    alt: "Obra titulada habitación  amarilla con pipa en 60x 40 cm del archivo 2000-09 por artista visual Enrique Ciapara",
    width: 363,
    height: 528,
    landscape: false,
    size: "w-[88%]",
    offsetX: 16,
    offsetY: -18,
    title: "Habitación amarilla con pipa",
    technique: "Mixta sobre papel",
    dimentions: "60 x 40 cm",
    date: "( 2023 )",
  },
  {
    src: "/images/blurb/historias de cocina mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Obra historias de cocina en técnica mixta sobre tela 183x 152 cm por artista visual  Enrique Ciapara",
    width: 399,
    height: 525,
    landscape: false,
    size: "w-[85%]",
    offsetX: -12,
    offsetY: 14,
    title: "Historias de cocina",
    technique: "Mixta sobre tela",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/la brigade mixta sobre tela 244x 183 cm 2009.webp",
    alt: "Pieza la brigada en técnica mixta sobre tela en 244 x 183 cm por artista visual Ciapara ",
    width: 397,
    height: 528,
    landscape: false,
    size: "w-[90%]",
    offsetX: 18,
    offsetY: -16,
    title: "La brigade",
    technique: "Mixta sobre tela",
    dimentions: "244 x 183 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/la obrera mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Pieza La obrera en técnica mixta sobre tela 183 x 152 cm por Enrique Ciapara",
    width: 379,
    height: 529,
    landscape: false,
    size: "w-full",
    offsetX: -16,
    offsetY: 18,
    title: "La obrera",
    technique: "Mixta sobre tela",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/lolita mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Pieza titulada lolita de archivo 2000-09 en técnica mixta en 183x 152 cm por Enrique Ciapara",
    width: 398,
    height: 529,
    landscape: false,
    size: "w-[88%]",
    offsetX: 14,
    offsetY: -14,
    title: "Lolita",
    technique: "Mixta sobre tela",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/mal arreglo mixta sobre papel 60x 40 cm 2003.webp",
    alt: "Mal arreglo en tecnica mixta sobre papel 60x 40 cm del artista mexicano enrique ciapara",
    width: 361,
    height: 529,
    landscape: false,
    size: "w-[85%]",
    offsetX: -10,
    offsetY: 16,
    title: "Mal arreglo",
    technique: "Mixta sobre papel",
    dimentions: "60 x 40 cm",
    date: "( 2003 )",
  },
  {
    src: "/images/blurb/nature morte mixta sobre tela 183x 152 cm 2006 .webp",
    alt: "Pieza Nature morte en técnica mixta sobre tela 183 x 152 cm por artista basado en Tijuana",
    width: 399,
    height: 526,
    landscape: false,
    size: "w-[90%]",
    offsetX: 16,
    offsetY: -18,
    title: "Nature morte",
    technique: "Mixta sobre tela",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/nina (la selva) mixta sobre tela 183x 152 cm 2009.webp",
    alt: "Obra titulada nina en técnica mixta sobre tela en dimensiones  183x 152 cm por Enrique Ciapara",
    width: 399,
    height: 528,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Nina (la selva)",
    technique: "Mixta sobre tela",
    dimentions: "183 x 152 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/noirceur mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Pieza titulada noirceur del artista mexicano Enrique Ciapara",
    width: 404,
    height: 529,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Noirceur",
    technique: "Mixta sobre tela",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/now you're here mixta sobre tela 244 x 183 cm 2009.webp",
    alt: "Pieza now you're here de Enrique Ciapara artista mexicano elaborado en técnica mixta sobre tela 244 x 183 cm ",
    width: 396,
    height: 528,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Now you're here",
    technique: "Mixta sobre tela",
    dimentions: "244 x 283 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/recuerdo de Pompeya mixta sobre papel 60x 40 cm 2002.webp",
    alt: "Obra titulada Recuerdo de Pompeya elaborada en técnica mixta sobre papel en dimensiones 60x 40 cm por Enrique Ciapara",
    width: 333,
    height: 529,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Recuerdo de Pompeya",
    technique: "Mixta sobre papel",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
  {
    src: "/images/blurb/recuerdo de sobremesa mixta sobre papel 122x 90 cm 2008.webp",
    alt: "Pieza titulada  recuerdo de sobremesa en técnica mixta sobre papel en 122 x 90 cm por Enrique Ciapara ",
    width: 377,
    height: 526,
    landscape: false,
    size: "w-full",
    offsetX: -10,
    offsetY: 16,
    title: "Recuerdo de sobremesa",
    technique: "Mixta sobre papel",
    dimentions: "122 x 90 cm",
    date: "( 2008 )",
  },
  {
    src: "/images/blurb/ry cayó mixta sobre tela 122x 107 2006.webp",
    alt: "Pieza titulada: ry cayó en técnica mixta sobre tela en 122 x 107 por pintor Enrique Ciapara",
    width: 474,
    height: 529,
    landscape: false,
    size: "w-[88%]",
    offsetX: 16,
    offsetY: -18,
    title: "Ry cayó",
    technique: "Mixta sobre tela",
    dimentions: "122 x 107 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sala de espera mixta sobre tela 213x 122 cm 2006.webp",
    alt: "Obra titulada sala de espera en técnica mixta sobre tela 213x 122 cm por artista mexicano Enrique Ciapara",
    width: 300,
    height: 526,
    landscape: false,
    size: "w-[85%]",
    offsetX: -12,
    offsetY: 14,
    title: "Sala de espera",
    technique: "Mixta sobre tela",
    dimentions: "213 x 122 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo acrilico sobre tela 200x 200 cm 1999.webp",
    alt: "Obra sin titulo del archivo 2000-09 elaborada en acrílico sobre tela 200x 200 cm de 1999 por Enrique Ciapara",
    width: 537,
    height: 527,
    landscape: false,
    size: "w-[90%]",
    offsetX: 18,
    offsetY: -16,
    title: "Sin título",
    technique: "Acrílico sobre tela",
    dimentions: "200 x 213 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/sin titulo acrilico sobre tela 213x 244 cm 2009.webp",
    alt: "Pieza sin título en acrílico sobre tela en 213 x 244 cm  del archivo 2000-09 por Enrique Ciapara",
    width: 617,
    height: 529,
    landscape: false,
    size: "w-full",
    offsetX: -16,
    offsetY: 18,
    title: "Sin título",
    technique: "Acrílico sobre tela",
    dimentions: "213 x 244 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre papel 122 x 90 cm 2008.webp",
    alt: "Obra sin titulo en técnica mixta sobre papel en 122 x 90 cm por enrique ciapara artista mexicano",
    width: 478,
    height: 527,
    landscape: false,
    size: "w-[88%]",
    offsetX: 14,
    offsetY: -14,
    title: "Sin título",
    technique: "Mixta sobre tela",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre papel 60 x 40 cm  2002.webp",
    alt: "Pieza sin título en técnica mixta sobre papel 60x 40 cm por artista visual Enrique Ciapara",
    width: 335,
    height: 527,
    landscape: false,
    size: "w-[85%]",
    offsetX: -10,
    offsetY: 16,
    title: "Sin título",
    technique: "Mixta sobre papel",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre tela 122x 107 2006.webp",
    alt: "Sin titulo en tecnica mixta sobre tela 122x 107 del artista Enrique Ciapara del archivo 2006 ",
    width: 473,
    height: 527,
    landscape: false,
    size: "w-[90%]",
    offsetX: 16,
    offsetY: -18,
    title: "Sin título",
    technique: "Mixta sobre tela",
    dimentions: "122 x 107 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre tela 122x 213 cm 2006.webp",
    alt: "Obra sin título en técnica mixta sobre tela 122 x 213 cm de Enrique Ciapara artista mexicano",
    width: 672,
    height: 379,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Sin título",
    technique: "Mixta sobre tela",
    dimentions: "122 x 213 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre tela 183x 152 cm 2006 .webp",
    alt: "Obra sin título en técnica mixta sobre tela 183 x 152 cm  del archivo 2000-09 por Enrique Ciapara",
    width: 391,
    height: 527,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Sin título",
    technique: "Mixta sobre tela",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Pieza sin título en técnica mixta sobre tela 183x 152 cm por artista mexicano Enrique Ciapara",
    width: 402,
    height: 526,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Sin título",
    technique: "Mixta sobre tela",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/taller mixta sobre papel 60x 40cm 2002 .webp",
    alt: "Obra titulada taller por artista basado en Tijuana Enrique Ciapara en técnica mixta sobre papel 60 x 40 cm año 2002 ",
    width: 365,
    height: 528,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Taller",
    technique: "Mixta sobre papel",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
];