export type GalleryImage = {
  src: string;
  alt: string;
  altFr: string;
  altCa: string;
  width: number;
  height: number;
  title: string;
  technique: string;
  dimentions: string;
  date: string;
};

export const images: GalleryImage[] = [
  {
    src: "/images/Trompe/Conoce la simultaneidad de las obras de enrique ciapara en trompe l’oeil (1).webp",
    alt: "Simultaneous works by Enrique Ciapara in Trompe-l'œil, exhibited at El Cubo, Tijuana, 2013",
    altFr: "Œuvres simultanées d'Enrique Ciapara dans Trompe-l'œil, exposées au El Cubo, Tijuana, 2013",
    altCa: "Obres simultànies d'Enrique Ciapara al Trompe-l'œil, exposades a El Cubo, Tijuana, 2013",
    width: 2560,
    height: 1718,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/DSC_0214.webp",
    alt: "Work on display in Enrique Ciapara's Trompe-l'œil exhibition in Tijuana",
    altFr: "Œuvre présentée dans l'exposition Trompe-l'œil d'Enrique Ciapara à Tijuana",
    altCa: "Obra exposada a l'exposició Trompe-l'œil d'Enrique Ciapara a Tijuana",
    width: 1718,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Enrique ciapara presento en 2013 su obra Trompe l´oeil.webp",
    alt: "Enrique Ciapara presented his Trompe-l'œil exhibition in Tijuana in 2013",
    altFr: "Enrique Ciapara a présenté son exposition Trompe-l'œil à Tijuana en 2013",
    altCa: "Enrique Ciapara va presentar la seva exposició Trompe-l'œil a Tijuana el 2013",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Escultura titulada panadero en la exposicion del 2013 en el cubo por el artista plastico enrique ciapara en tijuana.webp",
    alt: "Sculpture titled Panadero (Baker) from Enrique Ciapara's exhibition at El Cubo, 2013",
    altFr: "Sculpture intitulée Panadero (Boulanger) de l'exposition d'Enrique Ciapara au El Cubo, 2013",
    altCa: "Escultura titulada Panadero (Forner) de l'exposició d'Enrique Ciapara a El Cubo, 2013",
    width: 1935,
    height: 2560,
    title: "Panadero",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Estudio de enrique ciapara en tijuana.webp",
    alt: "Studio of visual artist Enrique Ciapara in Tijuana",
    altFr: "Atelier de l'artiste visuel Enrique Ciapara à Tijuana",
    altCa: "Estudi de l'artista visual Enrique Ciapara a Tijuana",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Exposición  de la obra titulada Trompe l´oeil de enrique ciapara.webp",
    alt: "Exhibition of the work titled Trompe-l'œil by Enrique Ciapara",
    altFr: "Exposition de l'œuvre intitulée Trompe-l'œil par Enrique Ciapara",
    altCa: "Exposició de l'obra titulada Trompe-l'œil per Enrique Ciapara",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/La exhibición trompe-l’oeil comprende obra de distintas épocas del artista Enrique Ciapara enfocadas en una reflexión.webp",
    alt: "Trompe-l'œil exhibition as a reflection on the nature of painting by Enrique Ciapara",
    altFr: "Exposition Trompe-l'œil comme réflexion sur la nature de la peinture par Enrique Ciapara",
    altCa: "Exposició Trompe-l'œil com a reflexió sobre la naturalesa de la pintura per Enrique Ciapara",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Mural expuesto en Trompe-L’oeil  en el   el CECUT el 6 de julio del 2013.webp",
    alt: "Mural piece from the Trompe-l'œil retrospective exhibition at CECUT",
    altFr: "Pièce murale de l'exposition rétrospective Trompe-l'œil au CECUT",
    altCa: "Peça mural de l'exposició retrospectiva Trompe-l'œil al CECUT",
    width: 2560,
    height: 1673,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Obra de trompe l´oeil por enrique ciapara en tijuana.webp",
    alt: "Work from the Trompe-l'œil exhibition by Enrique Ciapara",
    altFr: "Œuvre de l'exposition Trompe-l'œil d'Enrique Ciapara",
    altCa: "Obra de l'exposició Trompe-l'œil d'Enrique Ciapara",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza de trompe l’oeil colgada en exposicion en el cubo.webp",
    alt: "Trompe-l'œil piece installed in the exhibition at El Cubo by Enrique Ciapara",
    altFr: "Pièce Trompe-l'œil installée dans l'exposition au El Cubo par Enrique Ciapara",
    altCa: "Peça Trompe-l'œil instal·lada a l'exposició a El Cubo per Enrique Ciapara",
    width: 2560,
    height: 1718,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza del enrique ciapara que presento en trompe-l’oeil en tijuana en la sala 3  del cubo en 2013.webp",
    alt: "Work exhibited in Trompe-l'œil by visual artist Enrique Ciapara in Tijuana, Sala 3 at El Cubo, 2013",
    altFr: "Œuvre exposée dans Trompe-l'œil par l'artiste visuel Enrique Ciapara à Tijuana, Sala 3 au El Cubo, 2013",
    altCa: "Obra exposada al Trompe-l'œil per l'artista visual Enrique Ciapara a Tijuana, Sala 3 a El Cubo, 2013",
    width: 1899,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza dentro de exhibicion trompe-l’oeil por  ciapara.webp",
    alt: "Work inside the Trompe-l'œil exhibition by Ciapara in Tijuana",
    altFr: "Œuvre présentée dans l'exposition Trompe-l'œil par Ciapara à Tijuana",
    altCa: "Obra dins l'exposició Trompe-l'œil per Ciapara a Tijuana",
    width: 1909,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza exhibida en Trompe l oei por enrique ciapara en el cubo tijuana.webp",
    alt: "Work exhibited in Trompe-l'œil by Enrique Ciapara at El Cubo, Tijuana",
    altFr: "Œuvre exposée dans Trompe-l'œil par Enrique Ciapara au El Cubo, Tijuana",
    altCa: "Obra exposada al Trompe-l'œil per Enrique Ciapara a El Cubo, Tijuana",
    width: 2560,
    height: 1780,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza por enrique ciapara  de su muestra trompe l' oeil de la expresion francesa engañar al ojo.webp",
    alt: "Work by Enrique Ciapara from his Trompe-l'œil exhibition — the French expression for 'deceiving the eye' — presented in 2013 at El Cubo",
    altFr: "Œuvre d'Enrique Ciapara issue de son exposition Trompe-l'œil — l'expression française pour « tromper l'œil » — présentée en 2013 au El Cubo",
    altCa: "Obra d'Enrique Ciapara de la seva exposició Trompe-l'œil — l'expressió francesa per a «enganyar l'ull» — presentada el 2013 a El Cubo",
    width: 2560,
    height: 1798,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza presentada en trompe-l’oei en tijuana por ciapara 2013.webp",
    alt: "Work inside the Trompe-l'œil exhibition by Ciapara in Tijuana",
    altFr: "Œuvre présentée dans l'exposition Trompe-l'œil par Ciapara à Tijuana",
    altCa: "Obra dins l'exposició Trompe-l'œil per Ciapara a Tijuana",
    width: 1892,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza titulada Ensenada exhibida en trompe-l’oeil por ciapara.webp",
    alt: "Work titled Ensenada exhibited in Trompe-l'œil by Ciapara, artist from Tijuana",
    altFr: "Œuvre intitulée Ensenada exposée dans Trompe-l'œil par Ciapara, artiste de Tijuana",
    altCa: "Obra titulada Ensenada exposada al Trompe-l'œil per Ciapara, artista de Tijuana",
    width: 664,
    height: 1000,
    title: "Ensenada",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza titulada dormido por ciapara exhibida en trompe-l’oeil en tijuana.webp",
    alt: "Work titled Dormido (Sleeping) by Ciapara exhibited in Trompe-l'œil at Sala 3, El Cubo, Tijuana, July 2013",
    altFr: "Œuvre intitulée Dormido (Endormi) par Ciapara exposée dans Trompe-l'œil à la Sala 3, El Cubo, Tijuana, juillet 2013",
    altCa: "Obra titulada Dormido (Adormit) per Ciapara exposada al Trompe-l'œil a la Sala 3, El Cubo, Tijuana, juliol 2013",
    width: 1897,
    height: 2560,
    title: "Dormido",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Piezas en hilera de la colección trompe l oeil 2013 de Enrique Ciapara.webp",
    alt: "Pieces in a row from Enrique Ciapara's Trompe-l'œil 2013 collection at El Cubo, Tijuana",
    altFr: "Œuvres alignées de la collection Trompe-l'œil 2013 d'Enrique Ciapara au El Cubo, Tijuana",
    altCa: "Obres alineades de la col·lecció Trompe-l'œil 2013 d'Enrique Ciapara a El Cubo, Tijuana",
    width: 2100,
    height: 1555,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Sala de exposiciones el cubo donde se expuso el trabajo del artista mexicano enrique ciapara.webp",
    alt: "El Cubo exhibition hall where the work of Mexican artist Enrique Ciapara was displayed",
    altFr: "Salle d'exposition El Cubo où fut présenté le travail de l'artiste mexicain Enrique Ciapara",
    altCa: "Sala d'exposicions El Cubo on es va exposar el treball de l'artista mexicà Enrique Ciapara",
    width: 2100,
    height: 1562,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Trompe l´oeil de enrique ciapara artista visual bajacaliforniano.webp",
    alt: "Trompe-l'œil exhibition presented in 2013 by Enrique Ciapara, visual artist from Baja California",
    altFr: "Exposition Trompe-l'œil présentée en 2013 par Enrique Ciapara, artiste visuel de Basse-Californie",
    altCa: "Exposició Trompe-l'œil presentada el 2013 per Enrique Ciapara, artista visual de Baixa Califòrnia",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
];
