export type GalleryImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  title: string;
  technique: string;
  dimentions: string;
  date: string;
};

export const images: GalleryImage[] = [
  {
    src: "/images/Trompe/Trompe l´oeil de enrique ciapara artista visual bajacaliforniano.jpg",
    alt: "Trompe-l'oeil exhibition presented in 2013 by Enrique Ciapara, visual artist from Baja California",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Estudio de enrique ciapara en tijuana.jpg",
    alt: "Studio of visual artist Enrique Ciapara in Tijuana",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza en exhibición de Trompe l´oeil de enrique ciapara.jpg",
    alt: "Work on display in Enrique Ciapara's Trompe-l'oeil exhibition in Tijuana",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Sección de exhibicion de enrique ciapara en el cubo 2013.webp",
    alt: "Section of Enrique Ciapara's exhibition at El Cubo, Tijuana, 2013",
    width: 2100,
    height: 1644,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Trompe l´oeil obra del artista enrique ciapara en tijuana.webp",
    alt: "Trompe-l'oeil work by artist Enrique Ciapara in Tijuana",
    width: 2100,
    height: 1644,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Enrique ciapara presento en 2013 su obra Trompe l´oeil.jpg",
    alt: "Enrique Ciapara presented his Trompe-l'oeil exhibition in Tijuana in 2013",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Exposición  de la obra titulada Trompe l´oeil de enrique ciapara.jpg",
    alt: "Exhibition of the work titled Trompe-l'oeil by Enrique Ciapara",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Fotografia intervenida por enrique ciapara parte de la exposicion de su obra trompe l´oeil.jpg",
    alt: "Intervened photograph by Enrique Ciapara, part of his Trompe-l'oeil exhibition",
    width: 1640,
    height: 1378,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Obra de trompe l´oeil por enrique ciapara en tijuana.jpg",
    alt: "Work from the Trompe-l'oeil exhibition by Enrique Ciapara",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Conoce la simultaneidad de las obras de enrique ciapara en trompe l'oeil.JPG",
    alt: "Simultaneous works by Enrique Ciapara in Trompe-l'oeil, exhibited at El Cubo, Tijuana, 2013",
    width: 2896,
    height: 1944,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Exhibicion en sala 3 de la galeria el cubo de enrique ciapara en 2013.jpg",
    alt: "Exhibition in Sala 3 of El Cubo gallery by Enrique Ciapara, 2013",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/TrompeL'oeil de enrique ciapara, bajo la curaduría Fernando Delmar, conocido en el mundo del arte como alberto dilge.jpg",
    alt: "Works exhibited in Trompe-l'oeil by Enrique Ciapara, curated by Fernando Delmar, known in the art world as Alberto Dilge",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Mural expuesto en Trompe-L'oeil  en el   el CECUT el 6 de julio del 2013.jpg",
    alt: "Mural piece from the Trompe-l'oeil retrospective exhibition at CECUT",
    width: 4236,
    height: 2769,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Trompe-L'oeil es una exposición que  comprende obra de distintas épocas de enrique ciapara.jpg",
    alt: "Works from different periods by Enrique Ciapara on display in Trompe-l'oeil",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/La exhibición trompe-l'oeil comprende obra de distintas épocas del artista Enrique Ciapara enfocadas en una reflexión.jpg",
    alt: "Trompe-l'oeil exhibition as a reflection on the nature of painting by Enrique Ciapara",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Vista de varias piezas de la exposicion trompe l'oeil por enrique ciapara y la curaduria de alberto dilge.jpg",
    alt: "Overview of works in the Trompe-l'oeil exhibition by Tijuana visual artist Enrique Ciapara, curated by Alberto Dilge",
    width: 4200,
    height: 2779,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza de trompe l'oeil colgada en exposicion en el cubo.JPG",
    alt: "Trompe-l'oeil piece installed in the exhibition at El Cubo by Enrique Ciapara",
    width: 2896,
    height: 1944,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Estudio de enrique ciapara donde se registro el proceso de Trompe I oeil.JPG",
    alt: "Enrique Ciapara's studio where the Trompe-l'oeil process was documented, a different approach to contemporary art",
    width: 2896,
    height: 1944,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Estudio de enrique ciapara 2013.jpg",
    alt: "Enrique Ciapara's studio in Tijuana, Baja California, 2013",
    width: 4288,
    height: 2848,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza exhibida en Trompe l oei por enrique ciapara en el cubo tijuana.jpg",
    alt: "Work exhibited in Trompe-l'oeil by Enrique Ciapara at El Cubo, Tijuana",
    width: 6001,
    height: 4172,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza por enrique ciapara  de su muestra trompe l' oeil de la expresion francesa engañar al ojo.jpg",
    alt: "Work by Enrique Ciapara from his Trompe-l'oeil exhibition — the French expression for 'deceiving the eye' — presented in 2013 at El Cubo",
    width: 6137,
    height: 4310,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza titulada Ensenada exhibida en trompe-l'oeil por ciapara.jpg",
    alt: "Work titled Ensenada exhibited in Trompe-l'oeil by Ciapara, artist from Tijuana",
    width: 664,
    height: 1000,
    title: "Ensenada",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza del enrique ciapara que presento en trompe-l'oeil en tijuana en la sala 3  del cubo en 2013.JPG",
    alt: "Work exhibited in Trompe-l'oeil by visual artist Enrique Ciapara in Tijuana, Sala 3 at El Cubo, 2013",
    width: 2670,
    height: 3600,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza dentro de exhibicion trompe-l'oeil por  ciapara.JPG",
    alt: "Work inside the Trompe-l'oeil exhibition by Ciapara in Tijuana",
    width: 2685,
    height: 3600,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza titulada dormido por ciapara exhibida en trompe-l'oeil en tijuana.JPG",
    alt: "Work titled Dormido (Sleeping) by Ciapara exhibited in Trompe-l'oeil at Sala 3, El Cubo, Tijuana, July 2013",
    width: 2668,
    height: 3600,
    title: "Dormido",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza presentada en trompe-l'oei en tijuana por ciapara 2013.JPG",
    alt: "Work inside the Trompe-l'oeil exhibition by Ciapara in Tijuana",
    width: 2660,
    height: 3600,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
];
