export type GalleryImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  landscape: boolean;
  size: string;
  offsetX: number;
  offsetY: number;
  title: string;
  technique: string;
  dimentions: string;
  date: string;
};

export const images: GalleryImage[] = [
  {
    src: "/images/blurb/Pieza titulada quince en tecnica mixta sobre tela 217x 122 cm 2001 por artista plastico enrique ciapara.webp",
    alt: "Piece titled Fifteen, mixed media on canvas, 217x 122 cm, created in 2001 by visual artist Enrique Ciapara, based in Tijuana",
    width: 341,
    height: 606,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Quince",
    technique: "Mixed media on canvas",
    dimentions: "217 x 122 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Pieza sin tiulo en acrilico sobre tela 217 x 122 cm por artista visual bajacaliforniano ciapara.webp",
    alt: "Untitled piece in acrylic on canvas, 217 x 122 cm, by Baja California visual artist Enrique Ciapara",
    width: 337,
    height: 605,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Sin título",
    technique: "Acrylic on canvas",
    dimentions: "217 x 122 cm",
    date: "-",
  },
  {
    src: "/images/blurb/Pieza detritus elaborada en acrilico sobre tela 217x 122 cm en 1999 por enrique ciapara.webp",
    alt: "Piece titled Detritus, made in acrylic on canvas, 217x 122 cm, in 1999 by Enrique Ciapara",
    width: 349,
    height: 604,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Detritus",
    technique: "Acrylic on canvas",
    dimentions: "217 x 122 cm",
    date: "( 1999 )",
  },
  {
    src: "/images/blurb/Pieza caminata en tecnica mixta sobre tela 183x 305 cm 2008 por enrique ciapara.webp",
    alt: "Piece titled Walk, mixed media on canvas, 183x 305 cm, made in 2008 by artist Enrique Ciapara",
    width: 770,
    height: 475,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Caminata",
    technique: "Mixed media on canvas",
    dimentions: "183 x 305 cm ",
    date: "( 2008 )",
  },
  {
    src: "/images/blurb/La despedida pieza en acrilico sobre tela en 122x 213 cm por Enrique Ciapara.webp",
    alt: "The Farewell, a piece made in acrylic on canvas, 122x 213 cm, by San Diego-Tijuana border artist Enrique Ciapara",
    width: 770,
    height: 442,
    landscape: false,
    size: "w-full",
    offsetX: -10,
    offsetY: 16,
    title: "La despedida",
    technique: "Acrylic on canvas",
    dimentions: "122 x 213 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/Pieza titulada detritus en tinta sobre papel 101x 406 cm elaborada en 2005 por artista mexicano enrique ciapara.webp",
    alt: "Piece titled Detritus, ink on paper, 101x 406 cm, made in 2005 by Mexican artist Enrique Ciapara",
    width: 770,
    height: 194,
    landscape: true,
    size: "w-full",
    offsetX: 0,
    offsetY: 0,
    title: "Detritus",
    technique: "Ink on paper",
    dimentions: "101 x 406 cm",
    date: "( 2005 )",
  },
  {
    src: "/images/blurb/Pieza sin titulo elaborada en tecnica mixta sobre papel en 130x 90 cm por arista abstracto enrique ciapara.webp",
    alt: "Untitled piece made in mixed media on paper, 130x 90 cm, by Mexican abstract artist Enrique Ciapara",
    width: 430,
    height: 609,
    landscape: false,
    size: "w-[85%]",
    offsetX: -12,
    offsetY: 14,
    title: "Sin título",
    technique: "Mixed media on paper",
    dimentions: "130 x 90 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Obra el inmortal  en tecnica mixta sobre papel en 130x 90 cm elaborada en 2001 por Enrique Ciapara artista de la frontera sandiego tijuana.webp",
    alt: "Work titled The Immortal, mixed media on paper, 130 x 90 cm, made in 2001 by visual artist Enrique Ciapara, who lives on the San Diego-Tijuana border",
    width: 452,
    height: 607,
    landscape: false,
    size: "w-[90%]",
    offsetX: 18,
    offsetY: -16,
    title: "El inmortal",
    technique: "Mixed media on paper",
    dimentions: "130 x 90 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Obra sin titulo  pieza en tecnica mixta sobre papel en 130x 90 cm por el pintor enrique ciapara.webp",
    alt: "Untitled work in mixed media on paper, 130x 90 cm, by Mexican painter Enrique Ciapara",
    width: 449,
    height: 603,
    landscape: false,
    size: "w-full",
    offsetX: -16,
    offsetY: 18,
    title: "Sin título",
    technique: "Mixed media on paper",
    dimentions: "130 x 90 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Avión y pimiento mixta sobre papel 60 x 40 cm 2002 .webp",
    alt: "Work titled Airplane and Pepper, mixed media on paper, 60x 40 cm, by Enrique Ciapara, artist from the Tijuana-San Diego region",
    width: 336,
    height: 529,
    landscape: false,
    size: "w-[88%]",
    offsetX: 14,
    offsetY: -14,
    title: "Avión y pimiento",
    technique: "Mixed media on paper",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
  {
    src: "/images/blurb/Imago mixta sobre tela 213x 122 cm 2001.webp",
    alt: "Imago, a piece in mixed media on canvas, 213 x 122 cm, by Mexican artist Enrique Ciapara",
    width: 611,
    height: 529,
    landscape: false,
    size: "w-[85%]",
    offsetX: -10,
    offsetY: 16,
    title: "Imago",
    technique: "Mixed media on canvas",
    dimentions: "213 x 122 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Las cosas y las sombras de las cosas mixta sobre tela 213 x 122 cm 2001 .webp",
    alt: "Work from Enrique Ciapara's archive titled Things and the Shadows of Things, mixed media on canvas, 213x 122 cm",
    width: 304,
    height: 525,
    landscape: false,
    size: "w-[90%]",
    offsetX: 16,
    offsetY: -18,
    title: "Las cosas y las sombras de las cosas",
    technique: "Mixed media on canvas",
    dimentions: "213 x 122 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/Sin titulo mixta sobre papel 60x 40 cm 2002.webp",
    alt: "Work from the 2000-09 archive by Enrique Ciapara, mixed media on paper, 60x 40 cm",
    width: 333,
    height: 527,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Sin título",
    technique: "Mixed media on paper",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
  {
    src: "/images/blurb/alt camp mixta sobre tela 213x 122 cm 2003.webp",
    alt: "Piece titled Alt camp, mixed media on canvas, 213x 122 cm, by Enrique Ciapara",
    width: 302,
    height: 528,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Alt camp",
    technique: "Mixed media on canvas",
    dimentions: "213 x 122 cm",
    date: "( 2003 )",
  },
  {
    src: "/images/blurb/delerrictus mixta sobre tela 213x 122 cm 2001.webp",
    alt: "Piece titled Delerrictus by Enrique Ciapara, mixed media on canvas, 213x 122 cm, from the 2000-09 archive",
    width: 294,
    height: 527,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Delerrictus",
    technique: "Mixed media on canvas",
    dimentions: "213 x 122 cm",
    date: "( 2001 )",
  },
  {
    src: "/images/blurb/dibujo mixta sobre tela 122x 107 cm 2006.webp",
    alt: "Piece titled Drawing, mixed media on canvas, 122x 107 cm, by painter Enrique Ciapara",
    width: 465,
    height: 528,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Dibujo",
    technique: "Mixed media on canvas",
    dimentions: "122 x 107 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/el conejo u el león mixta sobre tela 200x 200 2005.webp",
    alt: "Piece titled The Rabbit and the Lion by Enrique Ciapara, mixed media on canvas, 200x200 cm, from the 2000-09 archive",
    width: 539,
    height: 528,
    landscape: false,
    size: "w-full",
    offsetX: -10,
    offsetY: 16,
    title: "El conejo en el león",
    technique: "Mixed media on canvas",
    dimentions: "200 x 200",
    date: "( 2005 )",
  },
  {
    src: "/images/blurb/habitación amarilla con pipa mixta sobre papel 60x 40 cm 2003.webp",
    alt: "Work titled Yellow Room with Pipe, 60x 40 cm, from the 2000-09 archive by visual artist Enrique Ciapara",
    width: 363,
    height: 528,
    landscape: false,
    size: "w-[88%]",
    offsetX: 16,
    offsetY: -18,
    title: "Habitación amarilla con pipa",
    technique: "Mixed media on paper",
    dimentions: "60 x 40 cm",
    date: "( 2023 )",
  },
  {
    src: "/images/blurb/historias de cocina mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Work titled Kitchen Stories, mixed media on canvas, 183x 152 cm, by visual artist Enrique Ciapara",
    width: 399,
    height: 525,
    landscape: false,
    size: "w-[85%]",
    offsetX: -12,
    offsetY: 14,
    title: "Historias de cocina",
    technique: "Mixed media on canvas",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/la brigade mixta sobre tela 244x 183 cm 2009.webp",
    alt: "Piece titled La brigade, mixed media on canvas, 244 x 183 cm, by visual artist Ciapara",
    width: 397,
    height: 528,
    landscape: false,
    size: "w-[90%]",
    offsetX: 18,
    offsetY: -16,
    title: "La brigade",
    technique: "Mixed media on canvas",
    dimentions: "244 x 183 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/la obrera mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Piece titled The Worker, mixed media on canvas, 183 x 152 cm, by Enrique Ciapara",
    width: 379,
    height: 529,
    landscape: false,
    size: "w-full",
    offsetX: -16,
    offsetY: 18,
    title: "La obrera",
    technique: "Mixed media on canvas",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/lolita mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Piece titled Lolita, from the 2000-09 archive, mixed media, 183x 152 cm, by Enrique Ciapara",
    width: 398,
    height: 529,
    landscape: false,
    size: "w-[88%]",
    offsetX: 14,
    offsetY: -14,
    title: "Lolita",
    technique: "Mixed media on canvas",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/mal arreglo mixta sobre papel 60x 40 cm 2003.webp",
    alt: "Bad Arrangement, mixed media on paper, 60x 40 cm, by Mexican artist Enrique Ciapara",
    width: 361,
    height: 529,
    landscape: false,
    size: "w-[85%]",
    offsetX: -10,
    offsetY: 16,
    title: "Mal arreglo",
    technique: "Mixed media on paper",
    dimentions: "60 x 40 cm",
    date: "( 2003 )",
  },
  {
    src: "/images/blurb/nature morte mixta sobre tela 183x 152 cm 2006 .webp",
    alt: "Piece titled Nature morte, mixed media on canvas, 183 x 152 cm, by a Tijuana-based artist",
    width: 399,
    height: 526,
    landscape: false,
    size: "w-[90%]",
    offsetX: 16,
    offsetY: -18,
    title: "Nature morte",
    technique: "Mixed media on canvas",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/nina (la selva) mixta sobre tela 183x 152 cm 2009.webp",
    alt: "Work titled Nina (the Jungle), mixed media on canvas, 183x 152 cm, by Enrique Ciapara",
    width: 399,
    height: 528,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Nina (la selva)",
    technique: "Mixed media on canvas",
    dimentions: "183 x 152 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/noirceur mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Piece titled Noirceur, by Mexican artist Enrique Ciapara",
    width: 404,
    height: 529,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Noirceur",
    technique: "Mixed media on canvas",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/now you're here mixta sobre tela 244 x 183 cm 2009.webp",
    alt: "Piece titled Now You're Here by Mexican artist Enrique Ciapara, mixed media on canvas, 244 x 183 cm",
    width: 396,
    height: 528,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Now you're here",
    technique: "Mixed media on canvas",
    dimentions: "244 x 283 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/recuerdo de Pompeya mixta sobre papel 60x 40 cm 2002.webp",
    alt: "Work titled Memory of Pompeii, mixed media on paper, 60x 40 cm, by Enrique Ciapara",
    width: 333,
    height: 529,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Recuerdo de Pompeya",
    technique: "Mixed media on paper",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
  {
    src: "/images/blurb/recuerdo de sobremesa mixta sobre papel 122x 90 cm 2008.webp",
    alt: "Piece titled After-dinner Memory, mixed media on paper, 122 x 90 cm, by Enrique Ciapara",
    width: 377,
    height: 526,
    landscape: false,
    size: "w-full",
    offsetX: -10,
    offsetY: 16,
    title: "Recuerdo de sobremesa",
    technique: "Mixed media on paper",
    dimentions: "122 x 90 cm",
    date: "( 2008 )",
  },
  {
    src: "/images/blurb/ry cayó mixta sobre tela 122x 107 2006.webp",
    alt: "Piece titled Ry Fell, mixed media on canvas, 122 x 107 cm, by painter Enrique Ciapara",
    width: 474,
    height: 529,
    landscape: false,
    size: "w-[88%]",
    offsetX: 16,
    offsetY: -18,
    title: "Ry cayó",
    technique: "Mixed media on canvas",
    dimentions: "122 x 107 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sala de espera mixta sobre tela 213x 122 cm 2006.webp",
    alt: "Work titled Waiting Room, mixed media on canvas, 213x 122 cm, by Mexican artist Enrique Ciapara",
    width: 300,
    height: 526,
    landscape: false,
    size: "w-[85%]",
    offsetX: -12,
    offsetY: 14,
    title: "Sala de espera",
    technique: "Mixed media on canvas",
    dimentions: "213 x 122 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo acrilico sobre tela 200x 200 cm 1999.webp",
    alt: "Untitled work from the 2000-09 archive, acrylic on canvas, 200x 200 cm, from 1999, by Enrique Ciapara",
    width: 537,
    height: 527,
    landscape: false,
    size: "w-[90%]",
    offsetX: 18,
    offsetY: -16,
    title: "Sin título",
    technique: "Acrylic on canvas",
    dimentions: "200 x 213 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/sin titulo acrilico sobre tela 213x 244 cm 2009.webp",
    alt: "Untitled piece in acrylic on canvas, 213 x 244 cm, from the 2000-09 archive, by Enrique Ciapara",
    width: 617,
    height: 529,
    landscape: false,
    size: "w-full",
    offsetX: -16,
    offsetY: 18,
    title: "Sin título",
    technique: "Acrylic on canvas",
    dimentions: "213 x 244 cm",
    date: "( 2009 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre papel 122 x 90 cm 2008.webp",
    alt: "Untitled work in mixed media on paper, 122 x 90 cm, by Mexican artist Enrique Ciapara",
    width: 478,
    height: 527,
    landscape: false,
    size: "w-[88%]",
    offsetX: 14,
    offsetY: -14,
    title: "Sin título",
    technique: "Mixed media on canvas",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre papel 60 x 40 cm  2002.webp",
    alt: "Untitled piece in mixed media on paper, 60x 40 cm, by visual artist Enrique Ciapara",
    width: 335,
    height: 527,
    landscape: false,
    size: "w-[85%]",
    offsetX: -10,
    offsetY: 16,
    title: "Sin título",
    technique: "Mixed media on paper",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre tela 122x 107 2006.webp",
    alt: "Untitled, mixed media on canvas, 122x 107 cm, by Enrique Ciapara, from the 2006 archive",
    width: 473,
    height: 527,
    landscape: false,
    size: "w-[90%]",
    offsetX: 16,
    offsetY: -18,
    title: "Sin título",
    technique: "Mixed media on canvas",
    dimentions: "122 x 107 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre tela 122x 213 cm 2006.webp",
    alt: "Untitled work in mixed media on canvas, 122 x 213 cm, by Mexican artist Enrique Ciapara",
    width: 672,
    height: 379,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Sin título",
    technique: "Mixed media on canvas",
    dimentions: "122 x 213 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre tela 183x 152 cm 2006 .webp",
    alt: "Untitled work in mixed media on canvas, 183 x 152 cm, from the 2000-09 archive, by Enrique Ciapara",
    width: 391,
    height: 527,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Sin título",
    technique: "Mixed media on canvas",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/sin titulo mixta sobre tela 183x 152 cm 2006.webp",
    alt: "Untitled piece in mixed media on canvas, 183x 152 cm, by Mexican artist Enrique Ciapara",
    width: 402,
    height: 526,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Sin título",
    technique: "Mixed media on canvas",
    dimentions: "183 x 152 cm",
    date: "( 2006 )",
  },
  {
    src: "/images/blurb/taller mixta sobre papel 60x 40cm 2002 .webp",
    alt: "Work titled Workshop by Tijuana-based artist Enrique Ciapara, mixed media on paper, 60 x 40 cm, year 2002",
    width: 365,
    height: 528,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Taller",
    technique: "Mixed media on paper",
    dimentions: "60 x 40 cm",
    date: "( 2002 )",
  },
];
