"use client";

import { useI18n } from "../../providers/i18nProvider";

export default function DescriptionTrompe() {
  const { locale } = useI18n();

  if (locale === "en") {
    return (
      <div className="text-lg text-[#1A1916]/45 leading-relaxed pr-6 flex flex-col gap-4 [&_p]:text-justify">
        <p>
          Enrique Ciapara&apos;s painting reclaims what does not belong to
          painting and articulates itself as a language that obeys no defined
          grammar. The words that come to mind when we observe his work
          establish a vocabulary of contours and colors where a circle can be
          the origin of an idea, an apple, or a star.
        </p>
        <p>
          The works gathered in this exhibition describe a threshold between all
          the possibilities that can be found beyond what we can see — beyond
          the landscape, in the direction of lines, like writing in the dark.
        </p>
        <p>
          Ciapara begins with a certainty and turns it into a lie. Color is the
          measure of all things: the day is black, the night white, and the sky
          as blue as an orange. But before painting, nothing is defined.
          Ciapara&apos;s painting does not represent what we see but what we
          might come to see — as if figures and forms lost their dimension and
          balance, and we had to begin again.
        </p>
        <p>
          Each work represents the first image that gives rise to the rest. In
          every canvas, the colors, the trees, the chairs reappear. Painting is
          part of nature — one more element that completes reality. It is the
          first image we hold from childhood. It is the first image of the
          sensation of speed as an attribute of color.
        </p>
        <p>
          Everything can be painted. Everything is outside, like the landscape
          that passes through the window when we travel by train — an image we
          do not face head-on but glimpse from the side, and that suddenly, in a
          mysterious way, becomes visible. As happens with the colors of the
          rainbow that blend into one another. Through painting we know that the
          rainbow is not, in essence, in the rain, nor in the eye that sees it —
          though it is generated by the rain, the sun, and the eye.
        </p>
        <p>
          To see is a way of walking. To traverse the paths where memories
          arrange themselves by likeness — between one form and another, between
          a tree and the image of its shadow. In this simultaneity, Ciapara
          confuses part with whole, and his work, like the rainbow, projects
          itself as a trompe l&apos;oeil:
        </p>
        <p className="italic">
          Just as the stone thrown into water becomes the center and origin of
          many circles — and just as sound spreads in circles through the air —
          so too a body placed in luminous air expands in circles and fills the
          surrounding parts with its infinite images, appearing whole in the
          whole and whole in the smallest of its parts. (Leonardo da Vinci,
          Treatise on Painting, 68 [A. 9b]).
        </p>
        <h2>
          Alberto Dilger
          <br />
          Curator
        </h2>
      </div>
    );
  }

  return (
    <div className="text-lg text-[#1A1916]/45 leading-relaxed pr-6 flex flex-col gap-4 [&_p]:text-justify">
      <p>
        La pintura de Enrique Ciapara recupera aquello que no le pertenece a la
        pintura y se articula como un lenguaje que no obedece a una gramática
        definida. Las palabras que vienen a nuestra mente cuando observamos su
        obra establecen un vocabulario de contornos y colores donde el círculo
        puede ser el origen de una idea, una manzana o una estrella.
      </p>
      <p>
        La obra que se reúne en esta exposición describe un límite entre todas
        las posibilidades que se pueden encontrar más allá de lo que alcanzamos
        a ver, más allá del paisaje, en la dirección de las líneas, como la
        escritura en la oscuridad.
      </p>
      <p>
        Ciapara parte de una certeza para convertirla en un mentira. El color es
        la medida de todas las cosas: el día es negro, la noche blanca y el
        cielo azul como una naranja. Pero antes de la pintura no hay nada
        definido. La pintura de Ciapara no representa lo que vemos sino lo que
        podemos llegar a ver. Como si las figuras o las formas perdieran su
        dimensión el equilibrio y tuviéramos que empezar de nuevo.
      </p>
      <p>
        Cada obra representa la primera imagen que da origen a las demás. En
        cada cuadro vuelven a aparecer los colores, los árboles o las sillas. La
        pintura forma parte de la naturaleza, como un elemento más que completa
        la realidad. Es la primera imagen que tenemos de nuestra infancia. Es la
        primera imagen de la sensación de la velocidad como un atributo del
        color.
      </p>
      <p>
        Todo se puede pintar. Todo está afuera, como el paisaje que atraviesa la
        ventana cuando viajamos en un tren. Es una imagen que no tenemos de
        frente sino de lado y que de repente, de una manera misteriosa, se hace
        visible. Tal como sucede con los colores del arco iris que se confunden
        entre sí. Por la pintura sabemos que el arco iris no es, por esencia, ni
        en la lluvia ni en el ojo que lo ve, si bien es generado por la lluvia,
        por el sol y por el ojo.
      </p>
      <p>
        Ver es una manera de caminar. Recorrer los caminos donde los recuerdos
        se ordenan a partir de la similitud entre una forma y otra, entre un
        árbol y la imagen de la sombra de ese árbol. En esta simultaneidad,
        Ciapara confunde la parte con el todo y su obra, como el arco iris, se
        proyecta como un trompe l&apos;oeil:
      </p>
      <p className="italic">
        Es así como la piedra que al agua fue arrojada se hace centro y motivo
        de numerosos círculos y así como el sonido se difunde en círculos a
        través del aire, así también un cuerpo dispuesto en el aire luminoso se
        expande circularmente y colma a las partes circundantes de sus infinitas
        imágenes, pareciendo completo en el todo y completo en la menor de sus
        partes. (Leonardo da Vinci, Tratado de la pintura, 68 [A. 9b]).
      </p>
      <h2>
        Alberto Dilger
        <br />
        Curador
      </h2>
    </div>
  );
}
