"use client";

import { useI18n } from "../../providers/i18nProvider";

export default function DescriptionTrompe() {
  const { locale } = useI18n();

  if (locale === "en") {
    return (
      <div className="text-lg text-[#1A1916]/45 leading-relaxed pr-6 flex flex-col gap-4 [&_p]:text-justify">
        <p>
          Enrique Ciapara&apos;s painting reclaims what does not belong to
          painting and articulates itself as a language that obeys no defined
          grammar. The words that come to mind when we observe his work
          establish a vocabulary of contours and colors where a circle can be
          the origin of an idea, an apple, or a star.
        </p>
        <p>
          The works gathered in this exhibition describe a threshold between all
          the possibilities that can be found beyond what we can see — beyond
          the landscape, in the direction of lines, like writing in the dark.
        </p>
        <p>
          Ciapara begins with a certainty and turns it into a lie. Color is the
          measure of all things: the day is black, the night white, and the sky
          as blue as an orange. But before painting, nothing is defined.
          Ciapara&apos;s painting does not represent what we see but what we
          might come to see — as if figures and forms lost their dimension and
          balance, and we had to begin again.
        </p>
        <p>
          Each work represents the first image that gives rise to the rest. In
          every canvas, the colors, the trees, the chairs reappear. Painting is
          part of nature — one more element that completes reality. It is the
          first image we hold from childhood. It is the first image of the
          sensation of speed as an attribute of color.
        </p>
        <p>
          Everything can be painted. Everything is outside, like the landscape
          that passes through the window when we travel by train — an image we
          do not face head-on but glimpse from the side, and that suddenly, in a
          mysterious way, becomes visible. As happens with the colors of the
          rainbow that blend into one another. Through painting we know that the
          rainbow is not, in essence, in the rain, nor in the eye that sees it —
          though it is generated by the rain, the sun, and the eye.
        </p>
        <p>
          To see is a way of walking. To traverse the paths where memories
          arrange themselves by likeness — between one form and another, between
          a tree and the image of its shadow. In this simultaneity, Ciapara
          confuses part with whole, and his work, like the rainbow, projects
          itself as a trompe l&apos;œil:
        </p>
        <p className="italic">
          Just as the stone thrown into water becomes the center and origin of
          many circles — and just as sound spreads in circles through the air —
          so too a body placed in luminous air expands in circles and fills the
          surrounding parts with its infinite images, appearing whole in the
          whole and whole in the smallest of its parts. (Leonardo da Vinci,
          Treatise on Painting, 68 [A. 9b]).
        </p>
        <h2>
          Alberto Dilger
          <br />
          Curator
        </h2>
      </div>
    );
  }

  if (locale === "fr") {
    return (
      <div className="text-lg text-[#1A1916]/45 leading-relaxed pr-6 flex flex-col gap-4 [&_p]:text-justify">
        <p>
          La peinture d&apos;Enrique Ciapara récupère ce qui n&apos;appartient
          pas à la peinture et s&apos;articule comme un langage qui n&apos;obéit
          à aucune grammaire définie. Les mots qui viennent à l&apos;esprit
          lorsque nous observons son œuvre établissent un vocabulaire de
          contours et de couleurs où le cercle peut être l&apos;origine
          d&apos;une idée, d&apos;une pomme ou d&apos;une étoile.
        </p>
        <p>
          Les œuvres rassemblées dans cette exposition décrivent une limite
          entre toutes les possibilités que l&apos;on peut trouver au-delà de
          ce que nous arrivons à voir — au-delà du paysage, dans la direction
          des lignes, comme l&apos;écriture dans l&apos;obscurité.
        </p>
        <p>
          Ciapara part d&apos;une certitude pour la transformer en mensonge. La
          couleur est la mesure de toutes choses : le jour est noir, la nuit
          blanche et le ciel aussi bleu qu&apos;une orange. Mais avant la
          peinture, rien n&apos;est défini. La peinture de Ciapara ne représente
          pas ce que nous voyons mais ce que nous pourrions en venir à voir —
          comme si les figures et les formes perdaient leur dimension et leur
          équilibre, et qu&apos;il nous fallait recommencer.
        </p>
        <p>
          Chaque œuvre représente la première image qui donne naissance aux
          suivantes. Dans chaque toile, les couleurs, les arbres, les chaises
          réapparaissent. La peinture fait partie de la nature — un élément de
          plus qui complète la réalité. C&apos;est la première image que nous
          retenons de l&apos;enfance. C&apos;est la première image de la
          sensation de vitesse comme attribut de la couleur.
        </p>
        <p>
          Tout peut être peint. Tout est dehors, comme le paysage qui passe par
          la fenêtre quand nous voyageons en train — une image que nous
          n&apos;avons pas face à nous mais de côté, et qui soudainement, de
          façon mystérieuse, devient visible. Comme il arrive avec les couleurs
          de l&apos;arc-en-ciel qui se confondent entre elles. Par la peinture
          nous savons que l&apos;arc-en-ciel n&apos;est pas, par essence, dans
          la pluie ni dans l&apos;œil qui le voit — bien qu&apos;il soit généré
          par la pluie, le soleil et l&apos;œil.
        </p>
        <p>
          Voir est une façon de marcher. Parcourir les chemins où les souvenirs
          s&apos;ordonnent à partir de la ressemblance — entre une forme et une
          autre, entre un arbre et l&apos;image de son ombre. Dans cette
          simultanéité, Ciapara confond la partie avec le tout et son œuvre,
          comme l&apos;arc-en-ciel, se projette comme un trompe-l&apos;œil :
        </p>
        <p className="italic">
          Ainsi la pierre jetée dans l&apos;eau devient le centre et le motif de
          nombreux cercles — et ainsi le son se diffuse en cercles à travers
          l&apos;air — de même un corps placé dans l&apos;air lumineux
          s&apos;étend circulairement et remplit les parties environnantes de ses
          infinies images, paraissant complet dans le tout et complet dans la
          moindre de ses parties. (Léonard de Vinci, Traité de la peinture, 68
          [A. 9b]).
        </p>
        <h2>
          Alberto Dilger
          <br />
          Commissaire d&apos;exposition
        </h2>
      </div>
    );
  }

  if (locale === "ca") {
    return (
      <div className="text-lg text-[#1A1916]/45 leading-relaxed pr-6 flex flex-col gap-4 [&_p]:text-justify">
        <p>
          La pintura d&apos;Enrique Ciapara recupera allò que no pertany a la
          pintura i s&apos;articula com un llenguatge que no obeeix cap gramàtica
          definida. Les paraules que venen a la ment quan observem la seva obra
          estableixen un vocabulari de contorns i colors on el cercle pot ser
          l&apos;origen d&apos;una idea, una poma o una estrella.
        </p>
        <p>
          Les obres reunides en aquesta exposició descriuen un límit entre totes
          les possibilitats que es poden trobar més enllà del que aconseguim
          veure — més enllà del paisatge, en la direcció de les línies, com
          l&apos;escriptura en la foscor.
        </p>
        <p>
          Ciapara parteix d&apos;una certesa per convertir-la en una mentida. El
          color és la mesura de totes les coses: el dia és negre, la nit blanca
          i el cel tan blau com una taronja. Però abans de la pintura, res no
          està definit. La pintura de Ciapara no representa el que veiem sinó el
          que podríem arribar a veure — com si les figures i les formes perdessin
          la seva dimensió i el seu equilibri, i haguéssim de tornar a començar.
        </p>
        <p>
          Cada obra representa la primera imatge que dóna origen a les altres.
          En cada tela, els colors, els arbres, les cadires tornen a aparèixer.
          La pintura forma part de la natura — un element més que completa la
          realitat. És la primera imatge que tenim de la infància. És la primera
          imatge de la sensació de velocitat com a atribut del color.
        </p>
        <p>
          Tot es pot pintar. Tot és a fora, com el paisatge que passa per la
          finestra quan viatgem en tren — una imatge que no tenim de front sinó
          de costat i que de sobte, d&apos;una manera misteriosa, es fa visible.
          Com passa amb els colors de l&apos;arc de Sant Martí que es confonen
          entre si. Per la pintura sabem que l&apos;arc de Sant Martí no és, per
          essència, a la pluja ni a l&apos;ull que el veu — tot i que és generat
          per la pluja, el sol i l&apos;ull.
        </p>
        <p>
          Veure és una manera de caminar. Recórrer els camins on els records
          s&apos;ordenen a partir de la semblança — entre una forma i una altra,
          entre un arbre i la imatge de la seva ombra. En aquesta simultaneïtat,
          Ciapara confon la part amb el tot i la seva obra, com l&apos;arc de
          Sant Martí, es projecta com un trompe l&apos;œil:
        </p>
        <p className="italic">
          Així la pedra llançada a l&apos;aigua es fa centre i motiu de nombrosos
          cercles — i així el so es difon en cercles a través de l&apos;aire —
          de la mateixa manera un cos col·locat a l&apos;aire lluminós
          s&apos;expandeix circularment i omple les parts circumdants de les
          seves infinites imatges, semblant complet en el tot i complet en la
          menor de les seves parts. (Leonardo da Vinci, Tractat de la pintura,
          68 [A. 9b]).
        </p>
        <h2>
          Alberto Dilger
          <br />
          Comissari
        </h2>
      </div>
    );
  }

  return (
    <div className="text-lg text-[#1A1916]/45 leading-relaxed pr-6 flex flex-col gap-4 [&_p]:text-justify">
      <p>
        La pintura de Enrique Ciapara recupera aquello que no le pertenece a la
        pintura y se articula como un lenguaje que no obedece a una gramática
        definida. Las palabras que vienen a nuestra mente cuando observamos su
        obra establecen un vocabulario de contornos y colores donde el círculo
        puede ser el origen de una idea, una manzana o una estrella.
      </p>
      <p>
        La obra que se reúne en esta exposición describe un límite entre todas
        las posibilidades que se pueden encontrar más allá de lo que alcanzamos
        a ver, más allá del paisaje, en la dirección de las líneas, como la
        escritura en la oscuridad.
      </p>
      <p>
        Ciapara parte de una certeza para convertirla en un mentira. El color es
        la medida de todas las cosas: el día es negro, la noche blanca y el
        cielo azul como una naranja. Pero antes de la pintura no hay nada
        definido. La pintura de Ciapara no representa lo que vemos sino lo que
        podemos llegar a ver. Como si las figuras o las formas perdieran su
        dimensión el equilibrio y tuviéramos que empezar de nuevo.
      </p>
      <p>
        Cada obra representa la primera imagen que da origen a las demás. En
        cada cuadro vuelven a aparecer los colores, los árboles o las sillas. La
        pintura forma parte de la naturaleza, como un elemento más que completa
        la realidad. Es la primera imagen que tenemos de nuestra infancia. Es la
        primera imagen de la sensación de la velocidad como un atributo del
        color.
      </p>
      <p>
        Todo se puede pintar. Todo está afuera, como el paisaje que atraviesa la
        ventana cuando viajamos en un tren. Es una imagen que no tenemos de
        frente sino de lado y que de repente, de una manera misteriosa, se hace
        visible. Tal como sucede con los colores del arco iris que se confunden
        entre sí. Por la pintura sabemos que el arco iris no es, por esencia, ni
        en la lluvia ni en el ojo que lo ve, si bien es generado por la lluvia,
        por el sol y por el ojo.
      </p>
      <p>
        Ver es una manera de caminar. Recorrer los caminos donde los recuerdos
        se ordenan a partir de la similitud entre una forma y otra, entre un
        árbol y la imagen de la sombra de ese árbol. En esta simultaneidad,
        Ciapara confunde la parte con el todo y su obra, como el arco iris, se
        proyecta como un trompe l&apos;œil:
      </p>
      <p className="italic">
        Es así como la piedra que al agua fue arrojada se hace centro y motivo
        de numerosos círculos y así como el sonido se difunde en círculos a
        través del aire, así también un cuerpo dispuesto en el aire luminoso se
        expande circularmente y colma a las partes circundantes de sus infinitas
        imágenes, pareciendo completo en el todo y completo en la menor de sus
        partes. (Leonardo da Vinci, Tratado de la pintura, 68 [A. 9b]).
      </p>
      <h2>
        Alberto Dilger
        <br />
        Curador
      </h2>
    </div>
  );
}
