export type GalleryImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  title: string;
  technique: string;
  dimentions: string;
  date: string;
};

export const images: GalleryImage[] = [
  {
    src: "/images/Trompe/Conoce la simultaneidad de las obras de enrique ciapara en trompe l’oeil (1).webp",
    alt: "Conoce la simultaneidad de las obras de enrique ciapara en trompe l'œil obra del 2013 exuesta en EL CUBO en Tijuana",
    width: 2560,
    height: 1718,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/DSC_0214.webp",
    alt: "Pieza en exhibición de Trompe l'œil de Enrique Ciapara en Tijuana",
    width: 1718,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Enrique ciapara presento en 2013 su obra Trompe l´oeil.webp",
    alt: "Enrique Ciapara presento en 2013 su obra Trompe l'œil en tijuana",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Escultura titulada panadero en la exposicion del 2013 en el cubo por el artista plastico enrique ciapara en tijuana.webp",
    alt: "Escultura titulada Panadero de la exposición de Enrique Ciapara en El Cubo, 2013",
    width: 1935,
    height: 2560,
    title: "Panadero",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Estudio de enrique ciapara en tijuana.webp",
    alt: "Estudio de artista visual  Enrique Ciapara en Tijuana",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Exposición  de la obra titulada Trompe l´oeil de enrique ciapara.webp",
    alt: "Exposición de la obra titulada Trompe l'œil de Enrique Ciapara",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/La exhibición trompe-l’oeil comprende obra de distintas épocas del artista Enrique Ciapara enfocadas en una reflexión.webp",
    alt: "La exhibición Trompe-L'œil  es una reflexión acerca de la naturaleza de la pintura por Enrique Ciapara",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Mural expuesto en Trompe-L’oeil  en el   el CECUT el 6 de julio del 2013.webp",
    alt: "Pieza mural de la exposición Trompe-L'œil una muestra retrospectiva de Ciapara",
    width: 2560,
    height: 1673,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Obra de trompe l´oeil por enrique ciapara en tijuana.webp",
    alt: "Exposición de la obra titulada  trompe l'œil por Enrique Ciapara",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza de trompe l’oeil colgada en exposicion en el cubo.webp",
    alt: "Pieza de trompe l'œil colgada en exposición del artista Enrique Ciapara en El CUBO",
    width: 2560,
    height: 1718,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza del enrique ciapara que presento en trompe-l’oeil en tijuana en la sala 3  del cubo en 2013.webp",
    alt: "Pieza  expuesta en  trompe-l'œil  exhibición del artista visual Enrique Ciapara  en Tijuana en la sala 3  del cubo en 2013",
    width: 1899,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza dentro de exhibicion trompe-l’oeil por  ciapara.webp",
    alt: "Pieza dentro de exhibición trompe-l'œil por  ciapara en la ciduad de Tijuana",
    width: 1909,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza exhibida en Trompe l oei por enrique ciapara en el cubo tijuana.webp",
    alt: "Pieza exhibida en Trompe l'œil por Enrique Ciapara en el cubo Tijuana",
    width: 2560,
    height: 1780,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza por enrique ciapara  de su muestra trompe l' oeil de la expresion francesa engañar al ojo.webp",
    alt: "Pieza por Enrique Ciapara  de su muestra trompe l'œil de la expresion francesa engañar al ojo presentada en 2013 en El CUBO",
    width: 2560,
    height: 1798,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza presentada en trompe-l’oei en tijuana por ciapara 2013.webp",
    alt: "Pieza dentro de exhibición trompe-l'œil por  ciapara en la ciduad de Tijuana",
    width: 1892,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza titulada Ensenada exhibida en trompe-l’oeil por ciapara.webp",
    alt: "Pieza titulada Ensenada exhibida en trompe-l'œil por ciapara artista de Tijuana",
    width: 664,
    height: 1000,
    title: "Ensenada",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Pieza titulada dormido por ciapara exhibida en trompe-l’oeil en tijuana.webp",
    alt: "Pieza titulada dormido por ciapara exhibida en trompe-l'œil en la sala 3 de El Cubo en tijuana julio del 2013",
    width: 1897,
    height: 2560,
    title: "Dormido",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Piezas en hilera de la colección trompe l oeil 2013 de Enrique Ciapara.webp",
    alt: "Piezas en hilera de la colección Trompe l'œil 2013 de Enrique Ciapara en El Cubo, Tijuana",
    width: 2100,
    height: 1555,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Sala de exposiciones el cubo donde se expuso el trabajo del artista mexicano enrique ciapara.webp",
    alt: "Sala de exposiciones de El Cubo donde se expuso el trabajo del artista mexicano Enrique Ciapara",
    width: 2100,
    height: 1562,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
  {
    src: "/images/Trompe/Trompe l´oeil de enrique ciapara artista visual bajacaliforniano.webp",
    alt: "Trompe l'œil  obra  presentada en 2013 por  Enrique Ciapara  artista visual bajacaliforniano",
    width: 2560,
    height: 1700,
    title: "",
    technique: "",
    dimentions: "",
    date: "2013",
  },
];
