export type GalleryImage = {
  src: string;
  alt: string;
  altEn: string;
  altFr: string;
  altCa: string;
  width: number;
  height: number;
  title: string;
  technique: string;
  dimentions: string;
  date: string;
};

export const images: GalleryImage[] = [
  {
    src: "/images/Vanitas/0Z2A9377.webp",
    alt: "Pieza 1 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 1 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 1 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 1 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/0Z2A9378.webp",
    alt: "Pieza 2 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 2 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 2 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 2 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/0Z2A9379.webp",
    alt: "Pieza 3 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 3 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 3 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 3 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/0Z2A9380.webp",
    alt: "Pieza 4 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 4 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 4 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 4 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/0Z2A9381.webp",
    alt: "Pieza 5 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 5 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 5 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 5 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/0Z2A9382.webp",
    alt: "Pieza 6 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 6 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 6 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 6 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/0Z2A9383.webp",
    alt: "Pieza 7 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 7 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 7 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 7 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/0Z2A9384.webp",
    alt: "Pieza 8 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 8 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 8 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 8 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/0Z2A9385.webp",
    alt: "Pieza 9 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 9 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 9 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 9 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/0Z2A9386.webp",
    alt: "Pieza 10 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 10 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 10 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 10 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 1717,
    height: 2560,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/3W0A8246.webp",
    alt: "Pieza 11 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 11 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 11 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 11 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1668,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/3W0A8258.webp",
    alt: "Pieza 12 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 12 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 12 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 12 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1668,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/3W0A8261.webp",
    alt: "Pieza 13 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 13 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 13 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 13 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1668,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/3W0A8266.webp",
    alt: "Pieza 14 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 14 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 14 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 14 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1668,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/3W0A8268.webp",
    alt: "Pieza 15 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 15 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 15 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 15 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1668,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/3W0A8272.webp",
    alt: "Pieza 16 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 16 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 16 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 16 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1668,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/3W0A8276.webp",
    alt: "Pieza 17 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 17 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 17 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 17 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1668,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/LuluMaterial_1edit.webp",
    alt: "Pieza 18 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 18 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 18 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 18 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1707,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/LuluMaterial_4edit.webp",
    alt: "Pieza 19 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 19 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 19 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 19 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1707,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/LuluMaterial_5.webp",
    alt: "Pieza 20 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 20 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 20 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 20 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1706,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/LuluMaterial_6.webp",
    alt: "Pieza 21 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 21 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 21 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 21 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1706,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/LuluMaterial_7edit.webp",
    alt: "Pieza 22 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 22 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 22 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 22 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1709,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
  {
    src: "/images/Vanitas/LuluMaterial_8edit.webp",
    alt: "Pieza 23 de la colección Vanitas de Enrique Ciapara",
    altEn: "Piece 23 from Enrique Ciapara's Vanitas collection",
    altFr: "Œuvre 23 de la collection Vanitas d'Enrique Ciapara",
    altCa: "Peça 23 de la col·lecció Vanitas d'Enrique Ciapara",
    width: 2560,
    height: 1709,
    title: "",
    technique: "",
    dimentions: "",
    date: "",
  },
];
