export type GalleryImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  landscape: boolean;
  size: string;
  offsetX: number;
  offsetY: number;
  title: string;
  technique: string;
  dimentions: string;
  date: string;
};

export const images: GalleryImage[] = [
  {
    src: "/images/2015/Pieza cipres acrilico sobre tela 122 x 80 cm  por enrique ciapara.webp",
    alt: "Piece titled Cypress, acrylic on canvas, 122 x 80 cm, by Mexican visual artist Enrique Ciapara, inspired by Tijuana's architecture",
    width: 223,
    height: 339,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Ciprés",
    technique: "Acrylic on canvas",
    dimentions: "122 x 80 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza Cielo acrilico sobre tela 213x 122 cm por ciapara artista basado en tijuana.webp",
    alt: "Piece titled Sky, made in acrylic on canvas, 213x 122 cm, by Tijuana-based artist Ciapara, inspired by street food signage",
    width: 344,
    height: 590,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Cielo",
    technique: "Acrylic on canvas",
    dimentions: "213 x 122 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza sunnyday en acrilico sobre tela 122x 107 cm por artista enrique ciapara.webp",
    alt: "Work titled Sunnyday, acrylic on canvas, 122x 107 cm, by Baja California artist Enrique Ciapara, inspired by Tijuana and the Spanish Mediterranean",
    width: 294,
    height: 339,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Sunnyday",
    technique: "Acrylic on canvas",
    dimentions: "122 x 107 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza ensenada acrilico sobre tela 213x 122 cm por artista de la frontera san diego tijuana.webp",
    alt: "Piece titled Ensenada, acrylic on canvas, 213x 122 cm, by a San Diego-Tijuana border artist, inspired by Ensenada, Baja California",
    width: 336,
    height: 592,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Ensenada",
    technique: "Acrylic on canvas",
    dimentions: "213 x 122 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza dulce del dia de brujas acrilico sobre tela 122x 141 cm por pintor enrique ciapara.webp",
    alt: "Piece titled Halloween Candy, acrylic on canvas, 122x 141 cm, by painter Enrique Ciapara",
    width: 392,
    height: 337,
    landscape: false,
    size: "w-full",
    offsetX: -10,
    offsetY: 16,
    title: "Dulces del día de brujas",
    technique: "Acrylic on canvas",
    dimentions: "122 x 141 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza paisaje acrilico sobre tela 122x 95 cm por artista enrique ciapara en tijuana.webp",
    alt: "Piece made in 2015 titled Landscape, acrylic on canvas, 122x 95 cm, by artist Enrique Ciapara in Tijuana",
    width: 263,
    height: 340,
    landscape: false,
    size: "w-[88%]",
    offsetX: 16,
    offsetY: -18,
    title: "Paisaje",
    technique: "Acrylic on canvas",
    dimentions: "122 x 95 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza 8bit acrilico sobre tela 124x 107 cm Por enrique ciapara artista plastico en tijuana.webp",
    alt: "Piece titled 8bit, made in acrylic on canvas, 124x 107 cm, by visual artist Enrique Ciapara in Tijuana, made during 2015",
    width: 296,
    height: 344,
    landscape: false,
    size: "w-[85%]",
    offsetX: -12,
    offsetY: 14,
    title: "8bit",
    technique: "Acrylic on canvas",
    dimentions: "124 x 107 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza lontananza acrilico sobre tela 122x 122 cm por enrique ciapara artista visual de bajacaliforniando.webp",
    alt: "Piece titled Lontananza, made in acrylic on canvas, 122x 122 cm, by Enrique Ciapara, Baja California visual artist",
    width: 339,
    height: 338,
    landscape: false,
    size: "w-[90%]",
    offsetX: 18,
    offsetY: -16,
    title: "Lontananza",
    technique: "Acrylic on canvas",
    dimentions: "122 x 122 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza gran cañon acrilico sobre tela 213x 122 cm por enrique ciapara.webp",
    alt: "Piece titled Grand Canyon, made in acrylic on canvas, 213x 122 cm, by Enrique Ciapara, abstract artist in Tijuana",
    width: 267,
    height: 348,
    landscape: false,
    size: "w-full",
    offsetX: -16,
    offsetY: 18,
    title: "Gran cañón",
    technique: "Acrylic on canvas",
    dimentions: "125 x 96 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Grits acrilico sobre tela 122x 107 cm 2015.webp",
    alt: "Work titled Grits, made on canvas, 122 x 80 cm, by painter Enrique Ciapara",
    width: 223,
    height: 337,
    landscape: false,
    size: "w-[88%]",
    offsetX: 14,
    offsetY: -14,
    title: "Grits",
    technique: "Acrylic on canvas",
    dimentions: "122 x 80 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Recuerdo de Magali acrilico sobre tela 125 x 107 cm 2015.webp",
    alt: "Work titled Memory of Magali from the 2015 series, acrylic on canvas, 125 x 107 cm, by Enrique Ciapara",
    width: 297,
    height: 347,
    landscape: false,
    size: "w-[85%]",
    offsetX: -10,
    offsetY: 16,
    title: "Recuerdo Magali",
    technique: "Acrylic on canvas",
    dimentions: "125 x 107 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Robot acrilico sobre tela 213x 122 cm 2015.webp",
    alt: "Piece titled Robot, made in acrylic on canvas, 213 x 122 cm, by Enrique Ciapara, from the 2015 series",
    width: 344,
    height: 592,
    landscape: false,
    size: "w-[90%]",
    offsetX: 16,
    offsetY: -18,
    title: "Robot",
    technique: "Acrylic on canvas",
    dimentions: "213 x 122 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/El globo acrilico sobre tela 144 x 103 cm 2015.webp",
    alt: "Piece titled The Balloon, made in acrylic on canvas, 144 x 103 cm, by visual artist Enrique Ciapara",
    width: 288,
    height: 400,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "El globo",
    technique: "Acrylic on canvas",
    dimentions: "144 x 103 cm",
    date: "( 2015 )",
  },
];
