export type GalleryImage = {
  src: string;
  lightboxSrc?: string;
  alt: string;
  width: number;
  height: number;
  landscape: boolean;
  size: string;
  offsetX: number;
  offsetY: number;
  title: string;
  technique: string;
  dimentions: string;
  date: string;
};

export const images: GalleryImage[] = [
  {
    src: "/images/2015/Pieza cipres acrilico sobre tela 122 x 80 cm  por enrique ciapara.webp",
    alt: "Pieza ciprés acrílico sobre tela 122 x 80 cm  por Enrique Ciapara artista visual mexicano inspirado en la arquitectura de Tijuana",
    width: 223,
    height: 339,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "Ciprés",
    technique: "Acrílico sobre tela",
    dimentions: "122 x 80 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza Cielo acrilico sobre tela 213x 122 cm por ciapara artista basado en tijuana.webp",
    alt: "Pieza Cielo elaborado en acrilico sobre tela 213x 122 cm por ciapara artista basado en tijuana, inspirado en rotulos de comida callejera",
    width: 344,
    height: 590,
    landscape: false,
    size: "w-[88%]",
    offsetX: 18,
    offsetY: -16,
    title: "Cielo",
    technique: "Acrílico sobre tela",
    dimentions: "213 x 122 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza sunnyday en acrilico sobre tela 122x 107 cm por artista enrique ciapara.webp",
    alt: "Obra sunnyday en acrílico sobre tela 122x 107 cm por artista baja californiano  Enrique Ciapara inspirado en Tijuana y el Mediterráneo español",
    width: 294,
    height: 339,
    landscape: false,
    size: "w-[85%]",
    offsetX: -16,
    offsetY: 18,
    title: "Sunnyday",
    technique: "Acrílico sobre tela",
    dimentions: "122 x 107 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza ensenada acrilico sobre tela 213x 122 cm por artista de la frontera san diego tijuana.webp",
    alt: "Pieza ensenada acrílico sobre tela 213x 122 cm por artista de la frontera San Diego Tijuana inspirado en Ensenada Baja California",
    width: 336,
    height: 592,
    landscape: false,
    size: "w-[90%]",
    offsetX: 14,
    offsetY: -14,
    title: "Ensenada",
    technique: "Acrílico sobre tela",
    dimentions: "213 x 122 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza dulce del dia de brujas acrilico sobre tela 122x 141 cm por pintor enrique ciapara.webp",
    alt: "Pieza dulce del dia de brujas acrilico sobre tela 122x 141 cm por pintor enrique ciapara",
    width: 392,
    height: 337,
    landscape: false,
    size: "w-full",
    offsetX: -10,
    offsetY: 16,
    title: "Dulces del día de brujas",
    technique: "Acrílico sobre tela",
    dimentions: "122 x 141 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza paisaje acrilico sobre tela 122x 95 cm por artista enrique ciapara en tijuana.webp",
    alt: "Pieza elaborada en 2015 titulada paisaje en  acrílico sobre tela 122x 95 cm por artista Enrique Ciapara en Tijuana",
    width: 263,
    height: 340,
    landscape: false,
    size: "w-[88%]",
    offsetX: 16,
    offsetY: -18,
    title: "Paisaje",
    technique: "Acrílico sobre tela",
    dimentions: "122 x 95 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza 8bit acrilico sobre tela 124x 107 cm Por enrique ciapara artista plastico en tijuana.webp",
    alt: "Pieza 8bit elaborado en  acrílico sobre tela 124x 107 cm Por Enrique ciapara artista plastico en tijuana elaborado durante 2015 ",
    width: 296,
    height: 344,
    landscape: false,
    size: "w-[85%]",
    offsetX: -12,
    offsetY: 14,
    title: "8bit",
    technique: "Acrílico sobre tela",
    dimentions: "124 x 107 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza lontananza acrilico sobre tela 122x 122 cm por enrique ciapara artista visual de bajacaliforniando.webp",
    alt: "Pieza titulada lontananza elaborada en acrílico sobre tela 122x 122 cm por Enrique Ciapara artista visual de bajacaliforniando",
    width: 339,
    height: 338,
    landscape: false,
    size: "w-[90%]",
    offsetX: 18,
    offsetY: -16,
    title: "Lontananza",
    technique: "Acrílico sobre tela",
    dimentions: "122 x 122 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Pieza gran cañon acrilico sobre tela 213x 122 cm por enrique ciapara.webp",
    alt: "Pieza gran cañon elaboradaen acrilico sobre tela 213x 122 cm por Enrique ciapara artista abstracto en Tijuana",
    width: 267,
    height: 348,
    landscape: false,
    size: "w-full",
    offsetX: -16,
    offsetY: 18,
    title: "Gran cañón",
    technique: "Acrílico sobre tela",
    dimentions: "125 x 96 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Grits acrilico sobre tela 122x 107 cm 2015.webp",
    alt: "Obras titulada Grits elaborado en tela en 122 x 80 cm por  el pintor Enrique Ciapara",
    width: 223,
    height: 337,
    landscape: false,
    size: "w-[88%]",
    offsetX: 14,
    offsetY: -14,
    title: "Grits",
    technique: "Acrílico sobre tela",
    dimentions: "122 x 80 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Recuerdo de Magali acrilico sobre tela 125 x 107 cm 2015.webp",
    alt: "Obra recuerdo de Magali de la serie 2015 en acrílico sobre tela por Enrique Ciapara en 125 x 107 cm",
    width: 297,
    height: 347,
    landscape: false,
    size: "w-[85%]",
    offsetX: -10,
    offsetY: 16,
    title: "Recuerdo Magali",
    technique: "Acrílico sobre tela",
    dimentions: "125 x 107 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/Robot acrilico sobre tela 213x 122 cm 2015.webp",
    alt: "Pieza titulada robot elaborada en acrílico sobre tela con dimensiones 213 x 122 cm por Enrique Ciapara de la serie 2015",
    width: 344,
    height: 592,
    landscape: false,
    size: "w-[90%]",
    offsetX: 16,
    offsetY: -18,
    title: "Robot",
    technique: "Acrílico sobre tela",
    dimentions: "213 x 122 cm",
    date: "( 2015 )",
  },
  {
    src: "/images/2015/El globo acrilico sobre tela 144 x 103 cm 2015.webp",
    alt: "Pieza El globo elaborada en acrílico sobre tela en 144 x 103 por el artista visual Enrique Ciapara",
    width: 288,
    height: 400,
    landscape: false,
    size: "w-full",
    offsetX: -12,
    offsetY: 14,
    title: "El globo",
    technique: "Acrílico sobre tela",
    dimentions: "144 x 103 cm",
    date: "( 2015 )",
  },
];
